spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chargify
    username: root
    password: Bineesh@2003!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
